### ISSUE TITLE
Update to current WP, and BS 4

### ISSUE THREAD

**Issue by papyr** [taniarascia/bootstrapblog#1]
Hi, this is probably the best article for theme developers _albeit a little outdated_, any chance you can update.

And can you please highlight how to cascade the custom css to the open source plugins?

thanks

**Comment by taniarascia** [comment]
Yeah, I need to get around to doing one for BS4.

**Comment by robsd** [comment]
Would also be interested in BS4 update for this theme, I like the new fonts better
